name: Build Firmware

on:
  push:
    branches:
      - main  # Triggered when changes are pushed to the 'main' branch
  pull_request:
    branches:
      - main  # Triggered for pull requests targeting the 'main' branch
  workflow_dispatch:  # Allows the workflow to be manually triggered

jobs:
  build:
    name: Build Firmware
    runs-on: ubuntu-latest  # Running on an Ubuntu runner
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2  # Checkout the repository code

      - name: Set up Zephyr SDK
        run: |
          wget https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.14.2/zephyr-sdk-0.14.2-linux-x86_64.tar.xz
          tar -xJf zephyr-sdk-0.14.2-linux-x86_64.tar.xz
          export ZEPHYR_TOOLCHAIN_VARIANT=zephyr
          export ZEPHYR_SDK_INSTALL_DIR=zephyr-sdk-0.14.2
          source $ZEPHYR_SDK_INSTALL_DIR/zephyr-env.sh  # Set up the Zephyr SDK environment

      - name: Set up west (Zephyr's meta-tool)
        run: |
          python3 -m pip install --upgrade pip  # Update pip
          pip install west  # Install west tool
          west init -l  # Initialize the west workspace
          west update  # Update the workspace

      - name: Configure and Build
        run: |
          west build -b nice_nano_v2 -s app --shield corne_left  # Directly build for nice_nano_v2 and corne_left

      - name: Upload Firmware Artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware-nice_nano_v2-corne_left  # Artifact name includes board and shield
          path: build/zephyr/zephyr.bin  # Path to the firmware binary
